//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wsb.pl/pn/lab4")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.wsb.pl/pn/lab4", IsNullable=false)]
public partial class osoba {
    
    private string imieField;
    
    private string nazwiskoField;
    
    private long peselField;
    
    private osobaAdres[] adresyField;
    
    /// <remarks/>
    public string imie {
        get {
            return this.imieField;
        }
        set {
            this.imieField = value;
        }
    }
    
    /// <remarks/>
    public string nazwisko {
        get {
            return this.nazwiskoField;
        }
        set {
            this.nazwiskoField = value;
        }
    }
    
    /// <remarks/>
    public long pesel {
        get {
            return this.peselField;
        }
        set {
            this.peselField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("adres", IsNullable=false)]
    public osobaAdres[] adresy {
        get {
            return this.adresyField;
        }
        set {
            this.adresyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wsb.pl/pn/lab4")]
public partial class osobaAdres {
    
    private string ulicaField;
    
    private string nrDomuField;
    
    private string nrLokaluField;
    
    private string miejscowoscField;
    
    /// <remarks/>
    public string ulica {
        get {
            return this.ulicaField;
        }
        set {
            this.ulicaField = value;
        }
    }
    
    /// <remarks/>
    public string nrDomu {
        get {
            return this.nrDomuField;
        }
        set {
            this.nrDomuField = value;
        }
    }
    
    /// <remarks/>
    public string nrLokalu {
        get {
            return this.nrLokaluField;
        }
        set {
            this.nrLokaluField = value;
        }
    }
    
    /// <remarks/>
    public string miejscowosc {
        get {
            return this.miejscowoscField;
        }
        set {
            this.miejscowoscField = value;
        }
    }
}
